# Nav2 params for SLAM mode (no AMCL / Map Server)
# ROS 2 Humble

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_bt_navigator/BtNavigator"]

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity: 0.0
    min_y_velocity: 0.0
    min_theta_velocity: 0.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller/ProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller/SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.1
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.3
      max_linear_acceleration: 0.8
      max_linear_deceleration: 0.8
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.2
      lookahead_time: 1.5
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      allow_reversing: false
      use_collision_detection: true
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785 # 45 deg
      regulate_min_lookahead_dist: true
      min_approach_linear_velocity: 0.05

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true   # SLAM 중 미탐색 영역 허용

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["SimpleSmoother"]
    SimpleSmoother:
      plugin: "nav2_smoother/ConstrainedSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    behaviors: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower/WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0.0

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    max_velocity: [0.6, 0.0, 1.2]    # [vx, vy, vtheta]
    min_velocity: [0.0, 0.0, 0.0]
    max_accel:    [0.8, 0.0, 1.5]
    max_decel:    [0.8, 0.0, 1.5]

# Costmaps
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      rolling_window: false
      track_unknown_space: true
      footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]
      transform_tolerance: 0.3
      update_frequency: 5.0
      publish_frequency: 2.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        enabled: false          # SLAM에서 정적지도층은 비활성화
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          expected_update_rate: 0.0
          clearing: true
          marking: true
          data_type: "LaserScan"
      inflation_layer:
        enabled: true
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      resolution: 0.05
      rolling_window: true
      width: 3.0
      height: 3.0
      footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]
      transform_tolerance: 0.3
      update_frequency: 10.0
      publish_frequency: 5.0
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          expected_update_rate: 0.0
          clearing: true
          marking: true
          data_type: "LaserScan"
      inflation_layer:
        enabled: true
        inflation_radius: 0.5
        cost_scaling_factor: 3.0

# Lifecycle manager to bring up Nav2 core (without map_server/amcl)
# (slam_toolbox는 별도 런치에서 켜짐)
lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: [
      "controller_server",
      "planner_server",
      "smoother_server",
      "behavior_server",
      "bt_navigator",
      "waypoint_follower",
      "velocity_smoother",
      "global_costmap",
      "local_costmap"
    ]